### ISSUE TITLE
This install hasn't worked for me please help

### ISSUE THREAD

**Issue by LorenBristowDKU** [Mac1327/dss_ds_init_setup-#12]
Hi there, I ran through this install procedure twice and still don't have a working version of DSS (or any version at all haha) on my laptop. I can re-install my desktop version, but perhaps whatever has happened has value for perfecting this setup so let me know if you'd like to investigate my situation

**Comment by Mac1327** [comment]
Any error messages? 
A description of the problem. 
A descroption of what happened during the installation
Keep in mind that the installer doesn't make an icon to open. The nodes are started via the terminal. In your terminal run 
~/Library/dss/design/bin/dss start

in your browser go to 
localhost:11500

Tell me what happens.

**Comment by LorenBristowDKU** [comment]
hi there, 

Running through the steps again. 

I get an error in the "Install Pyenv and python 🐍" step
Logs:
`Last login: Fri Nov  4 10:44:15 on console
/Users/loren/.zshrc:source:75: no such file or directory: /Users/loren/.oh-my-zsh/oh-my-zsh.sh
/Users/loren/.zshrc:116: bad assignment
loren@Lorens-MacBook-Pro ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Mac1327/dss_ds_init_setup-/main/scripts/siliconornot.sh)"
💻You're using Intel processor💻 (ignore the Mac Silicon stuff)
loren@Lorens-MacBook-Pro ~ % xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
loren@Lorens-MacBook-Pro ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Mac1327/dss_ds_init_setup-/main/scripts/step1a.sh)"
==> Checking for `sudo` access (which may request your password)...
Password:
Sorry, try again.
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /usr/sbin/chown -R loren:admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
remote: Enumerating objects: 2128, done.
remote: Counting objects: 100% (919/919), done.
remote: Total 2128 (delta 919), reused 919 (delta 919), pack-reused 1209
Receiving objects: 100% (2128/2128), 962.31 KiB | 2.51 MiB/s, done.
Resolving deltas: 100% (1521/1521), completed with 344 local objects.
From https://github.com/Homebrew/brew
 * [new branch]          dependabot/bundler/Library/Homebrew/rubocop-1.38.0 -> origin/dependabot/bundler/Library/Homebrew/rubocop-1.38.0
 * [new branch]          less-agressive-core-tap -> origin/less-agressive-core-tap
   fb52a1214..759ab2d0b  master                  -> origin/master
 * [new tag]             3.6.5                   -> 3.6.5
 * [new tag]             3.6.10                  -> 3.6.10
 * [new tag]             3.6.11                  -> 3.6.11
 * [new tag]             3.6.6                   -> 3.6.6
 * [new tag]             3.6.7                   -> 3.6.7
 * [new tag]             3.6.8                   -> 3.6.8
 * [new tag]             3.6.9                   -> 3.6.9
Updating files: 100% (3437/3437), done.
HEAD is now at 759ab2d0b Merge pull request #14159 from Bo98/env-shebang
Updated 2 taps (homebrew/core and homebrew/cask).
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (nor will any be during this install run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Next steps:
- Run brew help to get started
- Further documentation:
    https://docs.brew.sh

Already up-to-date.
==> Upgrading 1 outdated package:
git 2.38.0 -> 2.38.1
==> Downloading https://ghcr.io/v2/homebrew/core/gettext/manifests/0.21.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/gettext/blobs/sha256:9318777367
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/git/manifests/2.38.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/git/blobs/sha256:d938a6f7023775
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Upgrading git
  2.38.0 -> 2.38.1 

==> Installing dependencies for git: gettext
==> Installing git dependency: gettext
==> Pouring gettext--0.21.1.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/gettext/0.21.1: 1,983 files, 20.6MB
==> Installing git
==> Pouring git--2.38.1.monterey.bottle.tar.gz
==> Caveats
The Tcl/Tk GUIs (e.g. gitk, git-gui) are now in the `git-gui` formula.
Subversion interoperability (git-svn) is now in the `git-svn` formula.

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/git/2.38.1: 1,592 files, 47.6MB
==> Running `brew cleanup git`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /usr/local/Cellar/git/2.38.0... (1,592 files, 47.6MB)
Removing: /Users/loren/Library/Caches/Homebrew/git--2.38.0... (17.5MB)
==> Upgrading 3 dependents of upgraded formulae:
Disable this behaviour by setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
imagemagick 7.1.0-50 -> 7.1.0-52, libheif 1.13.0_1 -> 1.14.0, libidn2 2.3.3 -> 2.3.4
==> Downloading https://ghcr.io/v2/homebrew/core/highway/manifests/1.0.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/highway/blobs/sha256:6f5347f6bb
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/imath/manifests/3.1.6
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/imath/blobs/sha256:9afc755be66e
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/lz4/manifests/1.9.4
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/lz4/blobs/sha256:88b369cea90a0a
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/zstd/manifests/1.5.2-3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/zstd/blobs/sha256:b0eabfa556c5a
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libde265/manifests/1.0.9
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libde265/blobs/sha256:2d258e7db
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libheif/manifests/1.14.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libheif/blobs/sha256:d521871772
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/fontconfig/manifests/2.14.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/fontconfig/blobs/sha256:e910d78
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/little-cms2/manifests/2.14
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/little-cms2/blobs/sha256:57a938
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libomp/manifests/15.0.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libomp/blobs/sha256:ff127958fb4
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/manifests/7.1.0-52
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/blobs/sha256:579988
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libidn2/manifests/2.3.4
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libidn2/blobs/sha256:335207a9dc
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Upgrading libheif
  1.13.0_1 -> 1.14.0 

==> Installing dependencies for libheif: highway, imath, lz4, zstd and libde265
==> Installing libheif dependency: highway
==> Pouring highway--1.0.2.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/highway/1.0.2: 61 files, 3.5MB
==> Installing libheif dependency: imath
==> Pouring imath--3.1.6.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/imath/3.1.6: 49 files, 927KB
==> Installing libheif dependency: lz4
==> Pouring lz4--1.9.4.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/lz4/1.9.4: 22 files, 685.2KB
==> Installing libheif dependency: zstd
==> Pouring zstd--1.5.2.monterey.bottle.3.tar.gz
🍺  /usr/local/Cellar/zstd/1.5.2: 31 files, 2.4MB
==> Installing libheif dependency: libde265
==> Pouring libde265--1.0.9.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/libde265/1.0.9: 22 files, 2.3MB
==> Installing libheif
==> Pouring libheif--1.14.0.monterey.bottle.tar.gz
==> /usr/local/opt/shared-mime-info/bin/update-mime-database /usr/local/share/mi
🍺  /usr/local/Cellar/libheif/1.14.0: 26 files, 2.8MB
==> Running `brew cleanup libheif`...
Removing: /usr/local/Cellar/libheif/1.13.0_1... (25 files, 2.7MB)
Removing: /Users/loren/Library/Caches/Homebrew/libheif--1.13.0_1... (1.3MB)
==> Upgrading imagemagick
  7.1.0-50 -> 7.1.0-52 

==> Installing dependencies for imagemagick: fontconfig, little-cms2 and libomp
==> Installing imagemagick dependency: fontconfig
==> Pouring fontconfig--2.14.1.monterey.bottle.tar.gz
==> Regenerating font cache, this may take a while
==> /usr/local/Cellar/fontconfig/2.14.1/bin/fc-cache -frv
🍺  /usr/local/Cellar/fontconfig/2.14.1: 88 files, 2.3MB
==> Installing imagemagick dependency: little-cms2
==> Pouring little-cms2--2.14.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/little-cms2/2.14: 21 files, 1.3MB
==> Installing imagemagick dependency: libomp
==> Pouring libomp--15.0.5.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/libomp/15.0.5: 7 files, 1.6MB
==> Installing imagemagick
==> Pouring imagemagick--7.1.0-52.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/imagemagick/7.1.0-52: 805 files, 28.5MB
==> Running `brew cleanup imagemagick`...
Removing: /usr/local/Cellar/imagemagick/7.1.0-50... (805 files, 28.5MB)
Removing: /Users/loren/Library/Caches/Homebrew/imagemagick--7.1.0-50... (10.2MB)
==> Upgrading libidn2
  2.3.3 -> 2.3.4 

==> Pouring libidn2--2.3.4.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/libidn2/2.3.4: 79 files, 1.2MB
==> Running `brew cleanup libidn2`...
Removing: /usr/local/Cellar/libidn2/2.3.3... (78 files, 987.8KB)
Removing: /Users/loren/Library/Caches/Homebrew/libidn2--2.3.3... (317.6KB)
==> Checking for dependents of upgraded formulae...
==> No broken dependents found!
==> Caveats
==> git
The Tcl/Tk GUIs (e.g. gitk, git-gui) are now in the `git-gui` formula.
Subversion interoperability (git-svn) is now in the `git-svn` formula.

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions
==> Upgrading 1 outdated package:
gh 2.17.0 -> 2.20.2
==> Downloading https://ghcr.io/v2/homebrew/core/gh/manifests/2.20.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/gh/blobs/sha256:c385e7cc5c95268
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Upgrading gh
  2.17.0 -> 2.20.2 

==> Pouring gh--2.20.2.monterey.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/gh/2.20.2: 147 files, 40.0MB
==> Running `brew cleanup gh`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /usr/local/Cellar/gh/2.17.0... (141 files, 35MB)
Removing: /Users/loren/Library/Caches/Homebrew/gh--2.17.0... (8MB)
Warning: wget 1.21.3 already installed
Warning: imagemagick 7.1.0-52 already installed
Warning: jq 1.6 already installed
==> Upgrading 1 outdated package:
openssl 3.0.5 -> 3.0.7
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/manifests/2022-
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/blobs/sha256:1b
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/manifests/3.0.7
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/blobs/sha256:8501aeea
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Upgrading openssl
  3.0.5 -> 3.0.7 

==> Installing dependencies for openssl@3: ca-certificates
==> Installing openssl@3 dependency: ca-certificates
==> Pouring ca-certificates--2022-10-11.all.bottle.tar.gz
==> Regenerating CA certificate bundle from keychain, this may take a while...
🍺  /usr/local/Cellar/ca-certificates/2022-10-11: 3 files, 225.5KB
==> Installing openssl@3
==> Pouring openssl@3--3.0.7.monterey.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@3/certs

and run
  /usr/local/opt/openssl@3/bin/c_rehash

openssl@3 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@3 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openssl@3/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@3 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@3/include"

For pkg-config to find openssl@3 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@3/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/openssl@3/3.0.7: 6,454 files, 28.3MB
==> Running `brew cleanup openssl@3`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /usr/local/Cellar/openssl@3/3.0.5... (6,444 files, 28.2MB)
Removing: /Users/loren/Library/Caches/Homebrew/openssl@3--3.0.5... (7.7MB)
==> Upgrading 3 dependents of upgraded formula:
Disable this behaviour by setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
openssl@1.1 1.1.1q -> 1.1.1s, pyenv 2.3.5 -> 2.3.6, python@3.7 3.7.14 -> 3.7.15
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/1.1/manifests/1.1.1s
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/1.1/blobs/sha256:d91517
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pyenv/manifests/2.3.6
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pyenv/blobs/sha256:4a3f7ba19389
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
Warning: python@3.7 has been deprecated because it is deprecated upstream!
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.7/manifests/3.7.15
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.7/blobs/sha256:7f07b85
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Upgrading openssl@1.1
  1.1.1q -> 1.1.1s 

==> Pouring openssl@1.1--1.1.1s.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/openssl@1.1/1.1.1s: 8,101 files, 18.5MB
==> Running `brew cleanup openssl@1.1`...
Removing: /usr/local/Cellar/openssl@1.1/1.1.1o... (8,089 files, 18.5MB)
Removing: /usr/local/Cellar/openssl@1.1/1.1.1q... (8,097 files, 18.5MB)
Removing: /Users/loren/Library/Caches/Homebrew/openssl@1.1--1.1.1o... (5.2MB)
Removing: /Users/loren/Library/Caches/Homebrew/openssl@1.1--1.1.1q... (5.2MB)
==> Upgrading pyenv
  2.3.5 -> 2.3.6 

==> Pouring pyenv--2.3.6.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/pyenv/2.3.6: 956 files, 3MB
==> Running `brew cleanup pyenv`...
Removing: /usr/local/Cellar/pyenv/2.3.5... (943 files, 3MB)
Removing: /Users/loren/Library/Caches/Homebrew/pyenv--2.3.5... (707.4KB)
==> Upgrading python@3.7
  3.7.14 -> 3.7.15 

==> Pouring python@3.7--3.7.15.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.7
Target /usr/local/bin/2to3-3.7
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3-3.7'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.7

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.7

Possible conflicting files are:
/usr/local/bin/2to3-3.7 -> /Library/Frameworks/Python.framework/Versions/3.7/bin/2to3-3.7
/usr/local/bin/idle3.7 -> /Library/Frameworks/Python.framework/Versions/3.7/bin/idle3.7
/usr/local/bin/pydoc3.7 -> /Library/Frameworks/Python.framework/Versions/3.7/bin/pydoc3.7
/usr/local/bin/python3.7 -> /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
/usr/local/bin/python3.7-config -> /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7-config
/usr/local/bin/python3.7m -> /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m
/usr/local/bin/python3.7m-config -> /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m-config
/usr/local/bin/pyvenv -> /Library/Frameworks/Python.framework/Versions/3.7/bin/pyvenv
/usr/local/bin/pyvenv-3.7 -> /Library/Frameworks/Python.framework/Versions/3.7/bin/pyvenv-3.7
==> /usr/local/Cellar/python@3.7/3.7.15/bin/python3.7 -s setup.py --no-user-cfg 
==> /usr/local/Cellar/python@3.7/3.7.15/bin/python3.7 -s setup.py --no-user-cfg 
==> /usr/local/Cellar/python@3.7/3.7.15/bin/python3.7 -s setup.py --no-user-cfg 
==> Caveats
Python has been installed as
  /usr/local/bin/python3.7

Unversioned and major-versioned symlinks `python`, `python3`, `python-config`, `python3-config`, `pip`, `pip3`, etc. pointing to
`python3.7`, `python3.7-config`, `pip3.7` etc., respectively, have been installed into
  /usr/local/opt/python@3.7/libexec/bin

You can install Python packages with
  pip3.7 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.7/site-packages

If you do not need a specific version of Python, and always want Homebrew's `python3` in your PATH:
  brew install python3

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python@3.7/3.7.15: 4,833 files, 76.6MB
==> Running `brew cleanup python@3.7`...
Removing: /usr/local/Cellar/python@3.7/3.7.14... (4,832 files, 76.7MB)
Removing: /Users/loren/Library/Caches/Homebrew/python@3.7--3.7.14... (17.8MB)
==> Checking for dependents of upgraded formulae...
==> No broken dependents found!
==> Caveats
==> openssl@3
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@3/certs

and run
  /usr/local/opt/openssl@3/bin/c_rehash

openssl@3 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@3 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openssl@3/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@3 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@3/include"

For pkg-config to find openssl@3 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@3/lib/pkgconfig"

==> python@3.7
Python has been installed as
  /usr/local/bin/python3.7

Unversioned and major-versioned symlinks `python`, `python3`, `python-config`, `python3-config`, `pip`, `pip3`, etc. pointing to
`python3.7`, `python3.7-config`, `pip3.7` etc., respectively, have been installed into
  /usr/local/opt/python@3.7/libexec/bin

You can install Python packages with
  pip3.7 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.7/site-packages

If you do not need a specific version of Python, and always want Homebrew's `python3` in your PATH:
  brew install python3

See: https://docs.brew.sh/Homebrew-and-Python
Running `brew update --auto-update`...
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

You have 1 outdated formula installed.
You can upgrade it with brew upgrade
or list it with brew outdated.

Warning: openssl@3 3.0.7 is already installed and up-to-date.
To reinstall 3.0.7, run:
  brew reinstall openssl@3
Warning: tree 2.0.4 already installed
==> Upgrading 1 outdated package:
ncdu 2.1.2 -> 2.2.1
==> Downloading https://ghcr.io/v2/homebrew/core/ncdu/manifests/2.2.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/ncdu/blobs/sha256:d9f2c3dc28184
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Upgrading ncdu
  2.1.2 -> 2.2.1 

==> Pouring ncdu--2.2.1.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/ncdu/2.2.1: 6 files, 604.9KB
==> Running `brew cleanup ncdu`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /usr/local/Cellar/ncdu/2.1.2... (6 files, 518.3KB)
Removing: /Users/loren/Library/Caches/Homebrew/ncdu--2.1.2... (234.2KB)
Warning: xz 5.2.7 already installed
Warning: readline 8.2.1 already installed
The $ZSH folder already exists (/Users/loren/.oh-my-zsh).

You ran the installer with the $ZSH setting or the $ZSH variable is
exported. You have 3 options:

1. Unset the ZSH variable when calling the installer:
   `ZSH= sh install.sh`
2. Install Oh My Zsh to a directory that doesn't exist yet:
   `ZSH=path/to/new/ohmyzsh/folder sh install.sh`
3. (Caution) If the folder doesn't contain important information,
   you can just remove it with `rm -r /Users/loren/.oh-my-zsh`

loren@Lorens-MacBook-Pro ~ % export TARGET_PYTHON_VERSION='3.7.9'

zsh -c "$(curl -fsSL https://raw.githubusercontent.com/Mac1327/dss_ds_init_setup-/main/scripts/step1b.sh)" -s $TARGET_PYTHON_VERSION

Warning: pyenv 2.3.6 is already installed and up-to-date.
To reinstall 2.3.6, run:
  brew reinstall pyenv
/Users/loren/.zshrc:source:75: no such file or directory: /Users/loren/.oh-my-zsh/oh-my-zsh.sh
/Users/loren/.zshrc:116: bad assignment
pyenv: /Users/loren/.pyenv/versions/3.7.9 already exists
continue with installation? (y/N) y
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.9.tar.xz...
-> https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tar.xz
Installing Python-3.7.9...
patching file Misc/NEWS.d/next/Build/2021-10-11-16-27-38.bpo-45405.iSfdW5.rst
patching file configure
patching file configure.ac
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.7.9 to /Users/loren/.pyenv/versions/3.7.9

All done!
/Users/loren/.zshrc:source:75: no such file or directory: /Users/loren/.oh-my-zsh/oh-my-zsh.sh
/Users/loren/.zshrc:116: bad assignment
loren@Lorens-MacBook-Pro ~ % export TARGET_PYTHON_VERSION='3.7.9'
export NAME_OF_NEW_ENV='dataiku'
git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
exec zsh
fatal: destination path '/Users/loren/.pyenv/plugins/pyenv-virtualenv' already exists and is not an empty directory.
/Users/loren/.zshrc:source:75: no such file or directory: /Users/loren/.oh-my-zsh/oh-my-zsh.sh
/Users/loren/.zshrc:116: bad assignment
loren@Lorens-MacBook-Pro ~ % 
`

**Comment by LorenBristowDKU** [comment]
Let me know if there's a better way to share the logs.

**Comment by LorenBristowDKU** [comment]
I've self-healed. Removed the directory pyenv-virtualenv and reran Python env piece. I now have DSS (although 404 on API service and no API key provided)
